# Generated by Django 6.0.5 on 2026-07-27 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('gateway', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='ID returned by the gateway once a transaction is created/completed.', max_length=255, null=True, unique=True)),
                ('gateway_reference', models.CharField(blank=True, help_text='Any secondary reference/token returned by the gateway.', max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='The booking this payment settles.', on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='bookings.booking')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['gateway'], name='payments_pa_gateway_dc3f0f_idx'), models.Index(fields=['gateway_transaction_id'], name='payments_pa_gateway_2a3159_idx')],
            },
        ),
    ]
