# Generated by Django 6.0.5 on 2026-07-12 12:58

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_picture_path, validators=[accounts.models.validate_image_upload]),
        ),
        migrations.CreateModel(
            name='MemberVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('citizenship', 'Citizenship card'), ('passport', 'Passport'), ('driving_license', 'Driving licence')], max_length=20)),
                ('document_number', models.CharField(max_length=100)),
                ('document_image', models.ImageField(upload_to=accounts.models.verification_document_path, validators=[accounts.models.validate_image_upload])),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
