# Generated by Django 6.0.5 on 2026-07-12 13:00

import accounts.models
import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_picture_memberverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberverification',
            name='document_image',
            field=models.ImageField(storage=accounts.storage.PrivateVerificationStorage(), upload_to=accounts.models.verification_document_path, validators=[accounts.models.validate_image_upload]),
        ),
    ]
